In [7]:
#necessary imports

import numpy as np
import matplotlib.pyplot as plt

#find the probability of winning for nxn matrix. Will do n= 2 and n = 3

def Winprob(dim, opener):
    move = int(dim**2/2)
    if dim % 2 == 1:
        if  opener == True: 
            matrix = np.array((1,)*move+(0,)*(move+1))
        else:
            matrix = np.array((1,)*(move+1)+(0,)*move)
    else:
        matrix = np.array((1,)*move+(0,)*move)
    wins = 0
    for i in range(10000):
        np.random.shuffle(matrix)
        det = np.linalg.det(np.reshape(matrix,(dim,dim))) 
        if det == 0:
            wins+=1
    return wins/10000

In [2]:
#find random probability for a 2x2
sum = 0
for i in range(20):
    sum += Winprob(2, True)
print(sum/20)




0.66744


In [3]:
#random probability for a 3x3.

sum = 0
for i in range(20):
    sum += Winprob(3, True)
print(sum/20)
#random probability for a 4x4

sum = 0
for i in range(20):
    sum += Winprob(3, True)
print(sum/20)

0.715405
0.7131000000000001


In [4]:
import numpy as np

print ("Here I am generating 2 different possible games for n=4 and n=6")
# -1 means empty cell for the start of game.
def generate_game(n):


    
    matrix = np.full((n, n), -1)

    # Check for determinant of zero after making moves.
    def checkdet(i, j):
        # Start filling up matrix with my goes
        answer = np.where(matrix == -1, 0, matrix)  
        answer[i, j] = 0
        return np.isclose(np.linalg.det(answer), 0)



    
    # Function to perform a move for me and friend.
    def domove(friend, entry):
        matrix[entry] = friend

 # generate the game
    for move in range(n * n):
        friend = move % 2
        empty_entries = np.argwhere(matrix == -1)
        if empty_entries.size > 0:
            if friend == 1:
                # friend places a 1.
                random_cell = empty_entries[np.random.choice(empty_entries.shape[0])]
                domove(1, random_cell)
            else:
                # For n >= 4, apply the mirror technique I explained.
                # We cannot do n< 4 as explained in rubric.
                if n >= 4:
                    done = False
                    for i in range(n):
                        for j in range(n // 2):
                            if matrix[i, j] == 1 and matrix[i, n - j - 1] == -1:
                                domove(0, (i, n - j - 1))
                                done = True
                                break
                    if done:
                            break
                    if not done:
                        # If reflection cannot be done, do 0 somewhere else. Explained in rubric.
                        for cell in empty_entries:
                            if checkdet(*cell):
                                domove(0, cell)
                                break
              

    # Check singularity of matrix. 
    det = np.linalg.det(np.where(matrix == -1, 0, matrix)) if -1 not in matrix else None
    return matrix, np.isclose(det, 0)

# generate the game for n=4 and n=6

results_n4 = generate_game(4)
results_n6 = generate_game(6)


print("matrix n=4:")
print(results_n4[0])
print("Determinant is zero:", results_n4[1])

print("matrix n=6:")
print(results_n6[0])
print("Determinant is zero:", results_n6[1])



   

Here I am generating 2 different possible games for n=4 and n=6
matrix n=4:
[[0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]
Determinant is zero: True
matrix n=6:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]]
Determinant is zero: True


In [6]:
print("test")

test
